# Excel Differ - Default Workflow Configuration
#
# This workflow is used when you run: python main.py workflow
# (without specifying a config file)
#
# Default behavior: Process local Excel files and output to local folder

# Logging configuration
logging:
  log_dir: ./logs

# State file configuration
state:
  file_path: ./tmp/state/.excel-differ-state.json

source:
  implementation: local_folder
  config:
    folder_path: ./tmp/input            # Input directory (create this folder)
    include_patterns:
      - "*.xlsx"
      - "*.xlsm"
      - "*.xlsb"
    exclude_patterns:
      - "**/~$*"          # Excel temp files
      - "**/.~lock.*"     # LibreOffice lock files

destination:
  implementation: local_folder
  config:
    folder_path: ./tmp/output           # Output directory (will be created)

converter:
  implementation: noop             # No conversion by default
  config: {}

flattener:
  implementation: openpyxl         # Use openpyxl flattener
  config:
    include_computed: false        # Don't include computed values (formulas only)
    include_literal: true          # Include literal values
    include_formats: true          # Include cell formatting
    include_origin_file: true      # Include original Excel file in flat output
    timeout: 3600                  # 1 hour timeout per file
    max_file_size_mb: 200          # Max file size: 200 MB
