# Excel Differ - Default Workflow Configuration
#
# This workflow is used when you run: python main.py workflow
# (without specifying a config file)
#
# Default behavior: Process local Excel files and output to local folder

# State file configuration
state:
  file_path: ./tmp/state/.excel-differ-state.json

source:
  implementation: local_folder
  config:
    folder_path: ./tmp/input            # Input directory (create this folder)
    include_patterns:
      - "*.xlsx"                    # Include .xlsx files in root
      - "*.xlsm"                    # Include .xlsm files in root
      - "**/*.xlsx"                 # Include .xlsx files in subdirectories
      - "**/*.xlsm"                 # Include .xlsm files in subdirectories
    exclude_patterns:
      - "**/~$*"                    # Exclude Excel temp files
      - "**/.~lock.*"               # Exclude LibreOffice lock files
      - "**/archive/**"             # Exclude archive folders
      - "**/backup/**"              # Exclude backup folders

destination:
  implementation: local_folder
  config:
    folder_path: ./tmp/output           # Output directory (will be created)

converter:
  implementation: noop             # No conversion by default
  config: {}

flattener:
  implementation: openpyxl         # Use openpyxl flattener
  config:
    include_computed: false        # Don't include computed values (formulas only)
    include_literal: true          # Include literal values
    include_formats: true          # Include cell formatting
    timeout: 900                   # 15 minute timeout per file
    max_file_size_mb: 200          # Max file size: 200 MB
